### ISSUE TITLE
TargetItem is always null

### ISSUE THREAD

**Issue by reediska** [punker76/gong-wpf-dragdrop#234] opened 2017-02-06 13:47 UTC
Since version 1.0.0, targetItem property of dropInfo parameter of Drop()-method is always null.

**Comment by punker76** [comment] 2017-02-06 13:49
@reediska In v1.1 too? Can you create a short sample which reproduces this issue? thx

**Comment by reediska** [comment] 2017-02-06 14:10
<ListView dd:DragDrop.IsDragSource="True" ItemsSource="{Binding Modules}" />

<ListView ItemsSource="{Binding Workflows}">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <Grid>
                        <ListView dd:DragDrop.IsDropTarget="True"
                                  dd:DragDrop.IsDragSource="True"
                                  dd:DragDrop.DragHandler="{Binding Main, Source={StaticResource Locator}}"
                                  dd:DragDrop.DropHandler="{Binding Main, Source={StaticResource Locator}}"
                                  ItemsSource="{Binding Modules}" />
                    </Grid>
                </DataTemplate>
            </ListView.ItemTemplate>
</ListView>

and ViewModel
...
        public void Drop(IDropInfo dropInfo)
        {

            var sourceItem = dropInfo.Data;
            var targetItem = dropInfo.TargetItem; //TargetItem is null
...

In v.0.1.4.3 published on nuget, dropInfo.TargetItem is correctly set, but in v1.0.0 and v1.1.0 it is always null

**Comment by punker76** [comment] 2017-02-06 14:16
@reediska Also if there are items in the second ListView?

**Comment by punker76** [comment] 2017-02-06 14:20
@reediska and you should give your inner ListView some MinHeight for a drop place

**Comment by punker76** [comment] 2017-02-06 14:21
@reediska look at the #146 sample at the demo

**Comment by reediska** [comment] 2017-02-17 10:31
The inner ListView has a StackPanel as ItemsPanelTemplate. If there are some items in the list and I drop a new element over an element inside the list, then the TargetItem is those element I droped new element over, but if I drop it just to empty space inside of the ListView, then TargetItem is null

**Comment by Algorithman** [comment] 2017-06-06 20:38
Same problem here, i can drop files into my control, but i can't move items, since targetItem is null.

**Comment by punker76** [comment] 2017-11-05 22:03
Should be fixed with https://github.com/punker76/gong-wpf-dragdrop/pull/266

**Closed by punker76** 2017-11-05 22:03 UTC
