### ISSUE TITLE
Lots of lagging when using touch drag and drop.

### ISSUE THREAD

**Issue by las-nsc** [punker76/gong-wpf-dragdrop#448] opened 2022-07-07 15:17 UTC
**Describe the bug**
We have implemented drag and drop using this library and tested it with mouse without any significant issues (except [this](https://github.com/punker76/gong-wpf-dragdrop/issues/159#issuecomment-1106219688)), but when it was deployed to the target hardware which uses touch, there was semi-random and significant lagging issues where it could take minutes to drag something across the screen.

**To Reproduce**
Unfortunately I can't share our code to demonstrate the issue, but I have tried to diagnose the issue myself by using the source for this library. Running performance diagnostics shows the majority of time spent on the `System.Windows.DragDrop.DoDragDrop` method, which seems to block the UI thread due to its synchronous nature and can't be offloaded to another thread due to needing access to the dragged item template. One thing I did try is to add `CacheMode = new BitmapCache();` to the `DragDropPreview` which _might_ have improved things a little, but I am still seeing noticable lagging occasionally.

**Expected behavior**
No significant lagging with touch, same as mouse.

**Screenshots**
It would have to be a video, but not sure if I can share. TBD

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H2

I'm not sure why the issue is only noticable when using touch and not mouse, and it doesn't seem to be directly caused by anything this library is doing itself (particularly as the touch code doesn't seem to do anything much different to mouse), but is core to how the library works. Has anyone seen this sort of issue before and have a workaround?

**Comment by las-nsc** [comment] 2022-07-07 17:01
Having looked closer at other issues, I believe this is a duplicate of #418

**Comment by dxh-sc** [comment] 2022-07-20 08:32
I have same issue

**Comment by punker76** [comment] 2022-08-30 07:06
Duplicate of #418

**Closed by punker76** 2022-08-30 07:06 UTC
Labels: Duplicate
