### ISSUE TITLE
Disabling drag'n'drop on buttons of subitem

### ISSUE THREAD

**Issue by dijkstra33** [punker76/gong-wpf-dragdrop#119] opened 2014-12-30 08:14 UTC
Hi! I have an ItemsControl in wpf with enabled dd(need dd between all elements independently of inclusion level). Some DataTemplates have buttons in it's structure. On first level of inclusion everything works fine, but when we go deeper (-_-): when root ItemsControl have ItemsControl in some DataTemplate, and this 2nd level DataTemplate have buttons in it's structure - I only can click this button with two clicks instead of one: first click is eat by dd.
With deeper levels of inclusion (3rd, 4th etc.) I have the same problem: buttons on this levels can only be clicked by two presses. 
Do you have some solution for such a problem ?

**Comment by punker76** [comment] 2015-01-17 15:20
@dijkstra33 I can't reproduce your issue. I've added an example `ItemsControl with ItemsControl and Buttons`. Can you look at this and give me any other tipps?
@matelich That's not the correct solution for it.

**Comment by dijkstra33** [comment] 2015-01-21 13:35
@punker76 here is my example: 
https://www.dropbox.com/s/56u6rpv0d567a41/BugSample.zip?dl=0

Sorry, I didn't say about recursiveness in first post.

**Comment by punker76** [comment] 2015-04-11 21:11
@dijkstra33 i tested your example with the latest 1.0.0 alpha and can't find any problems, so maybe this issue is fixed now...

**Closed by punker76** 2015-04-11 21:11 UTC

**Comment by dijkstra33** [comment] 2015-04-13 07:41
Yes, you've fixed it. Thanks a lot!
