### ISSUE TITLE
Insert position calculates improperly for expanded TreeViewItem

### ISSUE THREAD

**Issue by ihormelnyk** [punker76/gong-wpf-dragdrop#103] opened 2014-06-26 16:29 UTC
Expanded TreeViewItem height includes child items also. So insert position should be calculated according to tree node itself but not whole tree item with sub nodes.

**Comment by hairybreeches** [comment] 2015-11-18 15:58
We are experiencing this problem too. 

To reproduce: 

1) Run the "defaults" example and switch to the tab labeled Issue #65.
2) Drag item 0 over the expanded element Root 1. 

Notice that wherever you hold item 0 over Root 1, you will always get the "insert" adorner, never the "add" adorner.

However, if you:
1) drag item 1 onto item 0, to add it.
2) expand item 0 (it should have one child)
3) drag item 2 over item 0.

Notice that in this case it is possible to get the "add" adorner.

When an expanded node has a small amount of children (seems like less than 3), it seems like it behaves roughly normally. 

However, when it has a larger amount of children, it seems like the InsertPosition is never set to be RelativeInsertPosition.TargetItemCenter, and so we never get the add adorner, only the insert adorner. This could well be a result of the problem noted above.

Is a fix for this issue in the works, or would you appreciate a pull request?

**Comment by punker76** [comment] 2015-11-18 16:14
@hairybreeches i'll take a look

**Comment by hairybreeches** [comment] 2015-11-18 16:39
Thanks! It looks like @IhorMelnyk is right, it's because the WPF item's height includes its children.

Although there's no really nice way to get the "true" item's height, when I use the solution outlined here

http://stackoverflow.com/questions/3354388/how-to-get-databound-treeviews-selected-treeviewitems-header-section-height-wit

I get the behaviour I would expect.

**Closed** 2017-01-17 16:43 UTC
